runtime: python39
env: standard

service: frontend

# Serve static React build files (assume built to 'build/' directory)
handlers:
  - url: /.*
    static_files: build/index.html
    upload: build/index.html
  - url: /(.*)
    static_files: build/\1
    upload: build/(.*)

# Environment variables (for VITE_API_URL pointing to backend)
env_variables:
  VITE_API_URL: "https://backend-dot-YOUR_PROJECT_ID.appspot.com/api/v1"

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 5