# Google Cloud App Engine configuration
runtime: custom
env: flex

# Backend service configuration
service: backend
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 10
  cool_down_period_sec: 60
  cpu_utilization:
    target_utilization: 0.6

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

env_variables:
  DB_HOST: "/cloudsql/PROJECT_ID:REGION:INSTANCE_NAME"
  DB_PORT: "5432"
  DB_USER: "postgres"
  DB_PASSWORD: "your-database-password"
  DB_NAME: "taskman"
  DB_SSL_MODE: "disable"  # Adjusted for Unix socket connections
  JWT_SECRET: "your-super-secret-jwt-key-change-this-in-production"
  JWT_EXPIRY: "24h"
  SERVER_PORT: "8080"
  SERVER_HOST: "0.0.0.0"
  LOG_LEVEL: "info"
  CORS_ALLOWED_ORIGINS: "https://YOUR_PROJECT_ID.appspot.com"  # Update to your frontend URL
  RUN_MIGRATIONS: "true"

# Health check configuration
readiness_check:
  path: "/health"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

liveness_check:
  path: "/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

# Network configuration
network:
  name: default