runtime: go121
env: standard

service: backend

# Environment variables from your .env
env_variables:
  DB_HOST: "aws-1-us-east-2.pooler.supabase.com"
  DB_PORT: "5432"
  DB_USER: "postgres.ahxqouifwuhbahbpuojp"
  DB_PASSWORD: "altok2004"
  DB_NAME: "postgres"
  DB_SSL_MODE: "require"
  SUPABASE_URL: "https://ahxqouifwuhbahbpuojp.supabase.co"
  SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFoeHFvdWlmd3VoYmFoYnB1b2pwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAxMTU4NjgsImV4cCI6MjA3NTY5MTg2OH0.k-Juck1qA-1LLkEaIXLYtH_G7iaAxxqN_1123NTS0f0"
  SUPABASE_SERVICE_ROLE_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFoeHFvdWlmd3VoYmFoYnB1b2pwIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDExNTg2OCwiZXhwIjoyMDc1NjkxODY4fQ.X-Of1oM1X0IqETfrI2jf8HhU9x_0JRXmS6kV9ILkxg4"
  JWT_SECRET: "NEhy72hq9WKTS1XofGh4+uDJlTLf6XszqHoyUnFUMUCP/A15BdIJTqHB/N2WZsaKX2h1UTHORcktSDZGP/alDA=="
  JWT_EXPIRY: "1h"
  SERVER_PORT: "8080"
  SERVER_HOST: "localhost"
  LOG_LEVEL: "info"
  CORS_ALLOWED_ORIGINS: "http://localhost:3000,http://localhost:8080,http://localhost:5173"
  RUN_MIGRATIONS: "false"

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 10